-- 0003_seed_biomarkers.sql
-- GENERATED FILE — do not edit by hand.
-- Source: scripts/biomarker-catalog.mjs  (regenerate with: node scripts/generate-seed.mjs)
-- Inserts the 71 built-in biomarkers. user_id IS NULL => built-in,
-- readable by everyone, writable by no one (see RLS in 0002_rls.sql).

insert into public.biomarkers
  (id, name, aliases, category, canonical_unit, alt_units, default_ranges, is_custom, user_id)
values
  ('total-cholesterol', 'Total Cholesterol', ARRAY['cholesterol', 'total chol', 'chol']::text[], 'LIPIDS', 'mg/dL', '[{"unit":"mmol/L","toCanonical":38.67}]'::jsonb, '[{"max":200}]'::jsonb, false, NULL),
  ('ldl-cholesterol', 'LDL Cholesterol', ARRAY['ldl', 'ldl-c', 'low density lipoprotein']::text[], 'LIPIDS', 'mg/dL', '[{"unit":"mmol/L","toCanonical":38.67}]'::jsonb, '[{"max":100}]'::jsonb, false, NULL),
  ('hdl-cholesterol', 'HDL Cholesterol', ARRAY['hdl', 'hdl-c', 'high density lipoprotein']::text[], 'LIPIDS', 'mg/dL', '[{"unit":"mmol/L","toCanonical":38.67}]'::jsonb, '[{"sex":"M","min":40},{"sex":"F","min":50}]'::jsonb, false, NULL),
  ('triglycerides', 'Triglycerides', ARRAY['trig', 'tg', 'trigs']::text[], 'LIPIDS', 'mg/dL', '[{"unit":"mmol/L","toCanonical":88.57}]'::jsonb, '[{"max":150}]'::jsonb, false, NULL),
  ('vldl-cholesterol', 'VLDL Cholesterol', ARRAY['vldl']::text[], 'LIPIDS', 'mg/dL', '[]'::jsonb, '[{"min":5,"max":40}]'::jsonb, false, NULL),
  ('non-hdl-cholesterol', 'Non-HDL Cholesterol', ARRAY['non hdl', 'non-hdl']::text[], 'LIPIDS', 'mg/dL', '[{"unit":"mmol/L","toCanonical":38.67}]'::jsonb, '[{"max":130}]'::jsonb, false, NULL),
  ('apolipoprotein-b', 'Apolipoprotein B', ARRAY['apob', 'apo b']::text[], 'LIPIDS', 'mg/dL', '[]'::jsonb, '[{"max":90}]'::jsonb, false, NULL),
  ('lipoprotein-a', 'Lipoprotein(a)', ARRAY['lp(a)', 'lpa']::text[], 'LIPIDS', 'mg/dL', '[]'::jsonb, '[{"max":30}]'::jsonb, false, NULL),
  ('fasting-glucose', 'Fasting Glucose', ARRAY['glucose', 'blood sugar', 'fbs', 'fasting blood glucose']::text[], 'GLUCOSE', 'mg/dL', '[{"unit":"mmol/L","toCanonical":18.0182}]'::jsonb, '[{"min":70,"max":99}]'::jsonb, false, NULL),
  ('hba1c', 'HbA1c', ARRAY['a1c', 'hemoglobin a1c', 'glycated hemoglobin']::text[], 'GLUCOSE', '%', '[]'::jsonb, '[{"min":4,"max":5.6}]'::jsonb, false, NULL),
  ('fasting-insulin', 'Fasting Insulin', ARRAY['insulin']::text[], 'GLUCOSE', 'µIU/mL', '[]'::jsonb, '[{"min":2.6,"max":24.9}]'::jsonb, false, NULL),
  ('c-peptide', 'C-Peptide', ARRAY['c peptide']::text[], 'GLUCOSE', 'ng/mL', '[]'::jsonb, '[{"min":0.8,"max":3.1}]'::jsonb, false, NULL),
  ('estimated-average-glucose', 'Estimated Average Glucose', ARRAY['eag']::text[], 'GLUCOSE', 'mg/dL', '[{"unit":"mmol/L","toCanonical":18.0182}]'::jsonb, '[{"min":70,"max":126}]'::jsonb, false, NULL),
  ('tsh', 'TSH', ARRAY['thyroid stimulating hormone', 'thyrotropin']::text[], 'THYROID', 'mIU/L', '[]'::jsonb, '[{"min":0.4,"max":4}]'::jsonb, false, NULL),
  ('free-t4', 'Free T4', ARRAY['ft4', 'free thyroxine']::text[], 'THYROID', 'ng/dL', '[]'::jsonb, '[{"min":0.8,"max":1.8}]'::jsonb, false, NULL),
  ('free-t3', 'Free T3', ARRAY['ft3', 'free triiodothyronine']::text[], 'THYROID', 'pg/mL', '[]'::jsonb, '[{"min":2.3,"max":4.2}]'::jsonb, false, NULL),
  ('total-t4', 'Total T4', ARRAY['t4', 'thyroxine']::text[], 'THYROID', 'µg/dL', '[]'::jsonb, '[{"min":5,"max":12}]'::jsonb, false, NULL),
  ('total-t3', 'Total T3', ARRAY['t3', 'triiodothyronine']::text[], 'THYROID', 'ng/dL', '[]'::jsonb, '[{"min":80,"max":200}]'::jsonb, false, NULL),
  ('tpo-antibodies', 'TPO Antibodies', ARRAY['anti-tpo', 'thyroid peroxidase antibodies']::text[], 'THYROID', 'IU/mL', '[]'::jsonb, '[{"max":9}]'::jsonb, false, NULL),
  ('thyroglobulin-antibodies', 'Thyroglobulin Antibodies', ARRAY['anti-tg', 'tg antibodies']::text[], 'THYROID', 'IU/mL', '[]'::jsonb, '[{"max":4}]'::jsonb, false, NULL),
  ('hemoglobin', 'Hemoglobin', ARRAY['hgb', 'hb', 'haemoglobin']::text[], 'CBC', 'g/dL', '[{"unit":"g/L","toCanonical":0.1}]'::jsonb, '[{"sex":"M","min":13.5,"max":17.5},{"sex":"F","min":12,"max":15.5}]'::jsonb, false, NULL),
  ('hematocrit', 'Hematocrit', ARRAY['hct', 'haematocrit']::text[], 'CBC', '%', '[]'::jsonb, '[{"sex":"M","min":41,"max":50},{"sex":"F","min":36,"max":44}]'::jsonb, false, NULL),
  ('white-blood-cells', 'White Blood Cells', ARRAY['wbc', 'leukocytes', 'white cell count']::text[], 'CBC', '10^3/µL', '[]'::jsonb, '[{"min":3.4,"max":10.8}]'::jsonb, false, NULL),
  ('red-blood-cells', 'Red Blood Cells', ARRAY['rbc', 'erythrocytes']::text[], 'CBC', '10^6/µL', '[]'::jsonb, '[{"sex":"M","min":4.35,"max":5.65},{"sex":"F","min":3.92,"max":5.13}]'::jsonb, false, NULL),
  ('platelets', 'Platelets', ARRAY['plt', 'platelet count']::text[], 'CBC', '10^3/µL', '[]'::jsonb, '[{"min":150,"max":450}]'::jsonb, false, NULL),
  ('mcv', 'MCV', ARRAY['mean corpuscular volume']::text[], 'CBC', 'fL', '[]'::jsonb, '[{"min":80,"max":100}]'::jsonb, false, NULL),
  ('mch', 'MCH', ARRAY['mean corpuscular hemoglobin']::text[], 'CBC', 'pg', '[]'::jsonb, '[{"min":27,"max":33}]'::jsonb, false, NULL),
  ('mchc', 'MCHC', ARRAY['mean corpuscular hemoglobin concentration']::text[], 'CBC', 'g/dL', '[]'::jsonb, '[{"min":32,"max":36}]'::jsonb, false, NULL),
  ('rdw', 'RDW', ARRAY['red cell distribution width']::text[], 'CBC', '%', '[]'::jsonb, '[{"min":11.5,"max":14.5}]'::jsonb, false, NULL),
  ('neutrophils', 'Neutrophils', ARRAY['neut', 'neutrophil']::text[], 'CBC', '%', '[]'::jsonb, '[{"min":40,"max":70}]'::jsonb, false, NULL),
  ('lymphocytes', 'Lymphocytes', ARRAY['lymph', 'lymphocyte']::text[], 'CBC', '%', '[]'::jsonb, '[{"min":20,"max":40}]'::jsonb, false, NULL),
  ('alt', 'ALT', ARRAY['alanine aminotransferase', 'sgpt']::text[], 'LIVER', 'U/L', '[]'::jsonb, '[{"min":7,"max":56}]'::jsonb, false, NULL),
  ('ast', 'AST', ARRAY['aspartate aminotransferase', 'sgot']::text[], 'LIVER', 'U/L', '[]'::jsonb, '[{"min":10,"max":40}]'::jsonb, false, NULL),
  ('alkaline-phosphatase', 'Alkaline Phosphatase', ARRAY['alp', 'alk phos']::text[], 'LIVER', 'U/L', '[]'::jsonb, '[{"min":44,"max":147}]'::jsonb, false, NULL),
  ('total-bilirubin', 'Total Bilirubin', ARRAY['bilirubin', 'tbil']::text[], 'LIVER', 'mg/dL', '[{"unit":"µmol/L","toCanonical":0.0585}]'::jsonb, '[{"min":0.1,"max":1.2}]'::jsonb, false, NULL),
  ('direct-bilirubin', 'Direct Bilirubin', ARRAY['conjugated bilirubin']::text[], 'LIVER', 'mg/dL', '[{"unit":"µmol/L","toCanonical":0.0585}]'::jsonb, '[{"max":0.3}]'::jsonb, false, NULL),
  ('albumin', 'Albumin', ARRAY['alb']::text[], 'LIVER', 'g/dL', '[{"unit":"g/L","toCanonical":0.1}]'::jsonb, '[{"min":3.5,"max":5}]'::jsonb, false, NULL),
  ('total-protein', 'Total Protein', ARRAY['protein total']::text[], 'LIVER', 'g/dL', '[{"unit":"g/L","toCanonical":0.1}]'::jsonb, '[{"min":6,"max":8.3}]'::jsonb, false, NULL),
  ('ggt', 'GGT', ARRAY['gamma-glutamyl transferase', 'gamma gt']::text[], 'LIVER', 'U/L', '[]'::jsonb, '[{"min":8,"max":61}]'::jsonb, false, NULL),
  ('creatinine', 'Creatinine', ARRAY['creat', 'cr']::text[], 'KIDNEY', 'mg/dL', '[{"unit":"µmol/L","toCanonical":0.0113}]'::jsonb, '[{"sex":"M","min":0.74,"max":1.35},{"sex":"F","min":0.59,"max":1.04}]'::jsonb, false, NULL),
  ('bun', 'BUN', ARRAY['blood urea nitrogen', 'urea nitrogen']::text[], 'KIDNEY', 'mg/dL', '[]'::jsonb, '[{"min":7,"max":20}]'::jsonb, false, NULL),
  ('egfr', 'eGFR', ARRAY['estimated gfr', 'glomerular filtration rate']::text[], 'KIDNEY', 'mL/min/1.73m²', '[]'::jsonb, '[{"min":60}]'::jsonb, false, NULL),
  ('uric-acid', 'Uric Acid', ARRAY['urate']::text[], 'KIDNEY', 'mg/dL', '[{"unit":"µmol/L","toCanonical":0.0168}]'::jsonb, '[{"sex":"M","min":3.4,"max":7},{"sex":"F","min":2.4,"max":6}]'::jsonb, false, NULL),
  ('cystatin-c', 'Cystatin C', ARRAY['cystatin']::text[], 'KIDNEY', 'mg/L', '[]'::jsonb, '[{"min":0.6,"max":1}]'::jsonb, false, NULL),
  ('sodium', 'Sodium', ARRAY['na']::text[], 'KIDNEY', 'mmol/L', '[]'::jsonb, '[{"min":135,"max":145}]'::jsonb, false, NULL),
  ('potassium', 'Potassium', ARRAY['k']::text[], 'KIDNEY', 'mmol/L', '[]'::jsonb, '[{"min":3.5,"max":5.2}]'::jsonb, false, NULL),
  ('chloride', 'Chloride', ARRAY['cl']::text[], 'KIDNEY', 'mmol/L', '[]'::jsonb, '[{"min":96,"max":106}]'::jsonb, false, NULL),
  ('bicarbonate', 'Bicarbonate', ARRAY['co2', 'carbon dioxide', 'hco3']::text[], 'KIDNEY', 'mmol/L', '[]'::jsonb, '[{"min":20,"max":29}]'::jsonb, false, NULL),
  ('calcium', 'Calcium', ARRAY['ca']::text[], 'KIDNEY', 'mg/dL', '[{"unit":"mmol/L","toCanonical":4.008}]'::jsonb, '[{"min":8.6,"max":10.3}]'::jsonb, false, NULL),
  ('phosphorus', 'Phosphorus', ARRAY['phosphate', 'po4']::text[], 'KIDNEY', 'mg/dL', '[]'::jsonb, '[{"min":2.5,"max":4.5}]'::jsonb, false, NULL),
  ('magnesium', 'Magnesium', ARRAY['mg']::text[], 'KIDNEY', 'mg/dL', '[{"unit":"mmol/L","toCanonical":2.43}]'::jsonb, '[{"min":1.7,"max":2.2}]'::jsonb, false, NULL),
  ('vitamin-d', 'Vitamin D (25-OH)', ARRAY['vitamin d', '25-oh vitamin d', '25 hydroxyvitamin d', 'vit d']::text[], 'VITAMINS', 'ng/mL', '[{"unit":"nmol/L","toCanonical":0.4}]'::jsonb, '[{"min":30,"max":100}]'::jsonb, false, NULL),
  ('vitamin-b12', 'Vitamin B12', ARRAY['b12', 'cobalamin']::text[], 'VITAMINS', 'pg/mL', '[{"unit":"pmol/L","toCanonical":1.355}]'::jsonb, '[{"min":200,"max":900}]'::jsonb, false, NULL),
  ('folate', 'Folate', ARRAY['folic acid', 'vitamin b9']::text[], 'VITAMINS', 'ng/mL', '[]'::jsonb, '[{"min":3}]'::jsonb, false, NULL),
  ('vitamin-b6', 'Vitamin B6', ARRAY['pyridoxine']::text[], 'VITAMINS', 'µg/L', '[]'::jsonb, '[{"min":5,"max":50}]'::jsonb, false, NULL),
  ('ferritin', 'Ferritin', ARRAY['ferritin level']::text[], 'IRON', 'ng/mL', '[]'::jsonb, '[{"sex":"M","min":24,"max":336},{"sex":"F","min":11,"max":307}]'::jsonb, false, NULL),
  ('serum-iron', 'Serum Iron', ARRAY['iron']::text[], 'IRON', 'µg/dL', '[{"unit":"µmol/L","toCanonical":5.587}]'::jsonb, '[{"sex":"M","min":65,"max":175},{"sex":"F","min":50,"max":170}]'::jsonb, false, NULL),
  ('tibc', 'TIBC', ARRAY['total iron binding capacity']::text[], 'IRON', 'µg/dL', '[]'::jsonb, '[{"min":250,"max":450}]'::jsonb, false, NULL),
  ('transferrin-saturation', 'Transferrin Saturation', ARRAY['tsat', 'iron saturation']::text[], 'IRON', '%', '[]'::jsonb, '[{"min":20,"max":50}]'::jsonb, false, NULL),
  ('transferrin', 'Transferrin', ARRAY['transferrin level']::text[], 'IRON', 'mg/dL', '[]'::jsonb, '[{"min":200,"max":360}]'::jsonb, false, NULL),
  ('testosterone-total', 'Total Testosterone', ARRAY['testosterone', 'total t']::text[], 'HORMONES', 'ng/dL', '[{"unit":"nmol/L","toCanonical":28.84}]'::jsonb, '[{"sex":"M","min":264,"max":916},{"sex":"F","min":8,"max":60}]'::jsonb, false, NULL),
  ('free-testosterone', 'Free Testosterone', ARRAY['free t']::text[], 'HORMONES', 'pg/mL', '[]'::jsonb, '[{"sex":"M","min":50,"max":210},{"sex":"F","min":1,"max":8.5}]'::jsonb, false, NULL),
  ('estradiol', 'Estradiol', ARRAY['e2', 'oestradiol']::text[], 'HORMONES', 'pg/mL', '[{"unit":"pmol/L","toCanonical":0.2724}]'::jsonb, '[{"min":15,"max":350}]'::jsonb, false, NULL),
  ('cortisol', 'Cortisol', ARRAY['am cortisol', 'morning cortisol']::text[], 'HORMONES', 'µg/dL', '[{"unit":"nmol/L","toCanonical":0.0362}]'::jsonb, '[{"min":6.2,"max":19.4}]'::jsonb, false, NULL),
  ('dhea-s', 'DHEA-S', ARRAY['dhea sulfate', 'dheas']::text[], 'HORMONES', 'µg/dL', '[]'::jsonb, '[{"min":35,"max":430}]'::jsonb, false, NULL),
  ('psa', 'PSA', ARRAY['prostate specific antigen']::text[], 'HORMONES', 'ng/mL', '[]'::jsonb, '[{"max":4}]'::jsonb, false, NULL),
  ('progesterone', 'Progesterone', ARRAY['prog']::text[], 'HORMONES', 'ng/mL', '[]'::jsonb, '[{"min":0.1,"max":25}]'::jsonb, false, NULL),
  ('crp', 'CRP', ARRAY['c-reactive protein']::text[], 'OTHER', 'mg/L', '[{"unit":"mg/dL","toCanonical":10}]'::jsonb, '[{"max":3}]'::jsonb, false, NULL),
  ('hs-crp', 'hs-CRP', ARRAY['high sensitivity crp', 'cardiac crp']::text[], 'OTHER', 'mg/L', '[{"unit":"mg/dL","toCanonical":10}]'::jsonb, '[{"max":1}]'::jsonb, false, NULL),
  ('homocysteine', 'Homocysteine', ARRAY['hcy']::text[], 'OTHER', 'µmol/L', '[]'::jsonb, '[{"max":15}]'::jsonb, false, NULL),
  ('esr', 'ESR', ARRAY['sed rate', 'erythrocyte sedimentation rate']::text[], 'OTHER', 'mm/hr', '[]'::jsonb, '[{"sex":"M","max":15},{"sex":"F","max":20}]'::jsonb, false, NULL)
on conflict (id) do update set
  name = excluded.name,
  aliases = excluded.aliases,
  category = excluded.category,
  canonical_unit = excluded.canonical_unit,
  alt_units = excluded.alt_units,
  default_ranges = excluded.default_ranges;
